### ISSUE TITLE
Push the rewrite

### ISSUE THREAD

**Issue by bggo** [bggo/Zmbkpose#21]
Liandros wrote the code from scratch. 

I just read it, need's someone to test.

**Comment by liandros** [comment]
Continue improving the documentation, and reviewing some details before commit.
Suggestions are welcome.

**Comment by marianstefan** [comment]
Hello Liandros,

I have tested you rewrite propossal from https://docs.google.com/open?id=0B9IDNSyRLvcBdVN4cWd6U2ZQUWc
First issue noticed was that restore doesn't work:

zmbkpose -r -a email
/bin/tar: 20120831115153: Cannot open: No such file or directory
/bin/tar: Error is not recoverable: exiting now

It seems that the restore function doesn't properly get the last backup time.

Regards,
Marian Stefan

**Comment by liandros** [comment]
2012/8/31 marianstefan notifications@github.com

> Hello Liandros,
> 
> I have tested you rewrite propossal from
> https://docs.google.com/open?id=0B9IDNSyRLvcBdVN4cWd6U2ZQUWc
> First issue noticed was that restore doesn't work:
> 
> zmbkpose -r -a email
> /bin/tar: 20120831115153: Cannot open: No such file or directory
> /bin/tar: Error is not recoverable: exiting now
> 
> It seems that the restore function doesn't properly get the last backup
> time.
> 
> Please, can you execute with
>   bash -x zmbkpose -r -a email
> and send me the last lines previous to error

**Comment by liandros** [comment]
Rewrite proposal pushed as a new branch "rewrite_proposal_v2.0"

**Comment by marianstefan** [comment]
Hello Liandros,

Nice to have you back. Here is the output of bash -x and ls -lsah

bash -x zmbkpose -r -a email

...
++ read date_time_mark full_inc bkfile
++ '[' -z 20120912115416 ']'
++ '[' 20120912115416 -gt 20120912115436 ']'
++ '[' -z '' -a FULL '!=' FULL ']'
++ '[' -z '' ']'
++ cycles_to_maintain_reached=y
++ continue
++ read date_time_mark full_inc bkfile
- restore_files=20120912115436
- '[' -z 20120912115436 ']'
- local last_backup
  ++ last_word 20120912115436
  ++ echo 20120912115436
  ++ /bin/sed '/^$/d'
  ++ /bin/sed 's/ /\n/g'
  ++ /bin/sed -n '$p'
- last_backup=20120912115436
- local ldap_data
  ++ /bin/tar -O -xf 20120912115436 acct.ldif
  /bin/tar: 20120912115436: Cannot open: No such file or directory
  /bin/tar: Error is not recoverable: exiting now
- ldap_data=

---

zimbra@mx01:~/backup/admin@mx.scsc.ro$ ls -lsah
total 20K
4.0K drwxr-x--- 2 zimbra zimbra 4.0K 2012-09-12 11:54 .
4.0K drwxr-xr-x 4 zimbra zimbra 4.0K 2012-09-12 11:54 ..
 12K -rw-r----- 1 zimbra zimbra  10K 2012-09-12 11:54
20120912115416:FULL.tar
   0 lrwxrwxrwx 1 zimbra zimbra   23 2012-09-12 11:54 LAST ->
20120912115416:FULL.tar

Regards,
Marian Stefan

**Comment by liandros** [comment]
The problem is caused by annoying debugging code.
However the new branch "rewrite_proposal_v2.0" is immune to this.
Additionally to give a complete solution to the problem, I created a new branch "issue_21".
Please... use the code in the branch "issue_21".
If the problem is solved, I will merge this on "rewrite_proposal_v2.0" branch.

**Comment by marianstefan** [comment]
Hello again,

The problem is solved now but others emerged while restoring: the script does no get the last backup cycle.
So if only one FULL it returns "No backup files available for restoration", if two FULL backups it will restore the oldest backup. If 3 full backups it will restore oldest 2 FULL but not the last.

zimbra@mx01:/backup/admin@scsc.ro$ ls -lsah
total 32K
4.0K drwxr-x--- 2 zimbra zimbra 4.0K 2012-09-17 15:54 .
4.0K drwxrwxrwx 4 root   root   4.0K 2012-09-17 15:54 ..
 12K -rw-r----- 1 zimbra zimbra  10K 2012-09-17 15:54 20120917155445:FULL.tar
 12K -rw-r----- 1 zimbra zimbra  10K 2012-09-17 15:54 20120917155453:INC.tar
   0 lrwxrwxrwx 1 zimbra zimbra   22 2012-09-17 15:54 LAST -> 20120917155453:INC.tar

+++ '[' '' = LAST -a -L /backup/admin@scsc.ro/LAST -a -f /backup/admin@scsc.ro/20120917155453:INC.tar ']'
+++ '[' -z '' ']'
+++ cat
+++ /usr/bin/sort -r
+++ cat
+++ /usr/bin/find /backup/admin@scsc.ro -maxdepth 1 -mindepth 1 -type f
+++ '[' '' = LAST ']'
+++ '[' '' = FIRST ']'
+++ cat
++ read date_time_mark full_inc bkfile
++ '[' -z 20120917155453 ']'
++ '[' 20120917155453 -gt 20120917160055 ']'
++ '[' -z '' -a INC '!=' FULL ']'
++ continue
++ read date_time_mark full_inc bkfile
++ '[' -z 20120917155445 ']'
++ '[' 20120917155445 -gt 20120917160055 ']'
++ '[' -z '' -a FULL '!=' FULL ']'
++ '[' -z '' ']'
++ cycles_to_maintain_reached=y
++ continue
++ read date_time_mark full_inc bkfile
- restore_files=
- '[' -z '' ']'
- debug 'admin@scsc.ro - No backup files available for restoration'
  ++ /bin/date '+%F %T'
- echo '2012-09-17 16:00:55 DEBUG: admin@scsc.ro - No backup files available for restoration '
  2012-09-17 16:00:55 DEBUG: admin@scsc.ro - No backup files available for restoration 
- return 0

**Comment by liandros** [comment]
Hello marianstefan. 
Thank you very much for your debugging and testing...

In restore, calling a erroneous function to get last cycle of backup. 
Was calling "get_backup_cycles_older_than" when it should call "get_last_backup_cycle_prior_to"

Branch issue_21  updated.  
Please update you code with the last version of branch.

**Comment by liandros** [comment]
Thank marianstefan for your tests.  I'll close for now this case.

**Comment by sanjivbjoshi** [comment]
hi
I have installed Zmbkpose-rewrite_proposal_v2.0. Everything working fine except one thing and it is
zmbkpose -backupdistributionlist command not working for backup all distribution list. So can you help me how to take backup of all distribution list. Already I have tried with following command
zmbkpose -backupdistributionlist, zmbkpose --backupdistributionlist, zmbkpose -f -backupdistributionlist, zmbkpose -f --backupdistributionlist.

**Comment by liandros** [comment]
-backupdistributionlist is not a valid option . Try --help .
There is no a option for backup only distribution lists. I will add thats
in plans. Thanks

2014-11-05 4:32 GMT-03:00 Sanjiv Joshi notifications@github.com:
