### ISSUE TITLE
"zmbkpose -d"  Do not exclude old full backups.

### ISSUE THREAD

**Issue by rodrigodelmonte** [bggo/Zmbkpose#31]
In a cron job I configure to zmbkpose exclude backups older than 15 days. But I noticed that just the incremental backups were excluded and the full backups still there. This behaviour is normal?

**Comment by liandros** [comment]
Hi. I don't understand the question mainly because the word "exclude". The -d option remove old backups cycles trying to avoid a disk full. 
A backup cycle is a full backup and subsequent incrementals. 
The entire cycle must be earlier than the date "now - argument_to_-d" to be removed. Then if you have : 
Day | Backup
1       FULL
2       INC
3       INC
4       INC
5       FULL
6       INC
7       FULL
8       FULL
Then you on day 9 execute zmbkpose with : 
  -d 2d  => backups of days 1,2,3,4,5,6  will be eliminated. because they are earlier to day 7  (9 - 2 = 7)
  -d 4d  => backups of days 1,2,3,4  will be eliminated. because they are earlier to day 5  (9 - 4 = 5)
  -d 5d  => no file will be deleted because it would break the cycle between days 1 to 4
If zmbkpose not work this way, then it is a bug. 
Try to test using "-s" argument for simulation, and not erase.
