### ISSUE TITLE
curl couldn't resolve host

### ISSUE THREAD

**Issue by mjo09a** [bggo/Zmbkpose#44]
When running zmbkpose -f I keep getting curl: (6) Couldn't resolve host ' '

**Comment by liandros** [comment]
There are 2 main branchs : master, and rewrite_proposal_v2.0  
Please. Can you tell me what branch are you using?

**Comment by neotheonce** [comment]
Me too having same error, but the log shows backup completed for all accounts
I am using Version 2.0 Beta - By William Felipe Welter 24/05/2012

**Comment by neotheonce** [comment]
Forgot to mention that I am using master branch

**Comment by liandros** [comment]
Apparently, in the master branch (I'm not a developer of master branch), a possible cause about it, is that an account does not have configured the ldap attribute "zimbraMailHost" .
You can list the zimbraMailDeliveryAddress , and zimbraMailHost attributes by each user using  : 

  source /etc/zmbkpose/zmbkpose.conf && $(which ldapsearch) -x -H $LDAPMASTERSERVER -D $LDAPZIMBRADN -w $LDAPZIMBRAPASS -b '' -LLL "(objectclass=zimbraAccount)" zimbraMailDeliveryAddress zimbraMailHost  | awk '/dn/ { if (length(ent) > 0) print ent; ent=""} /^zimbra/ {ent=(ent " " $2)'}

if any account without a corresponding attribute zimbraMailHost (second column), then that is the problem email account
~

**Comment by dagazz** [comment]
Hi, do you fix this issue? I'm having the same problem, with ldapsearch i get 
 mail.example.com raphael@example.com
 mail.example.com
 sidney@example.com
 mail.example.com carina@example.com

I think the problem is sidney's account, but, i get the attribute zimbraMailHost
dn: uid=sidney,ou=people,dc=example,dc=com
zimbraMailHost: mail.example.com
zimbraMailDeliveryAddress: sidney@example.com

Can you give me a help?? Thanks a lot.

**Comment by neotheonce** [comment]
I changed the branch. to rewrite_proposal_v2.0. This code is more robust. Still one issue with this  branch is, it does not detect auth failure for admin account and just creates all zip files.
